Iter9
AntonBezemskiy/go-musthave-metrics pull request #9
Opened 2024-07-30 19:16 UTC by AntonBezemskiy

2024-08-02 13:42 UTC, tmvrus requested changes
Хорошая работа, но есть несколько вопросов

2024-08-02 13:42 UTC, tmvrus commented on cmd/server/main.go
> +	time.Sleep(100 * time.Millisecond)
а зачем это?

2024-08-02 13:42 UTC, tmvrus commented on cmd/server/main.go
> +		time.Sleep(saver.GetStoreInterval() * time.Second)
`saver.GetStoreInterval() * time.Second` можно вычислить 1 раз перед входом в цикл

2024-08-02 13:42 UTC, tmvrus commented on internal/agent/compress/compress.go
> +		"application/javascript",
а где это используется?

2024-08-02 13:42 UTC, tmvrus commented on internal/agent/handlers/handlers.go
> +	}
потерян return

2024-08-02 13:42 UTC, tmvrus commented on internal/agent/handlers/handlers.go
> +		er := PushJSON(address, action, typeMetric, metricName, value, client)
а что запушит этот код если была ошибка при  получении метрики?

2024-08-02 13:42 UTC, tmvrus commented on internal/server/saver/saver.go
> +// // Сохраняю метрики в буфер для последующей записи в файл
закоменченого кода в готовом проекте быть не должно, это замусоривать и усложняет чтение

2024-08-02 17:25 UTC, AntonBezemskiy commented on cmd/server/main.go
> +	time.Sleep(100 * time.Millisecond)
Осталось с предыдущих версий реализации, удалил в 4ecd677e696dba1350739d70617154f9f3ef3a38.

2024-08-02 17:26 UTC, AntonBezemskiy commented on cmd/server/main.go
> +		time.Sleep(saver.GetStoreInterval() * time.Second)
Исправил в 4ecd677e696dba1350739d70617154f9f3ef3a38.

2024-08-02 17:30 UTC, AntonBezemskiy commented on internal/agent/compress/compress.go
> +		"application/javascript",
Добавил использование в 4ecd677e696dba1350739d70617154f9f3ef3a38.  
Перенес из internal/agent/compress/compress.go в internal/server/compress/compress.go.

2024-08-02 17:31 UTC, AntonBezemskiy commented on internal/agent/handlers/handlers.go
> +	}
Добавил return в 4ecd677e696dba1350739d70617154f9f3ef3a38.

2024-08-02 17:35 UTC, AntonBezemskiy commented on internal/agent/handlers/handlers.go
> +		er := PushJSON(address, action, typeMetric, metricName, value, client)
Добавил continue, в случае возникновения ошибки при получении метрики в 4ecd677e696dba1350739d70617154f9f3ef3a38.

2024-08-02 17:37 UTC, AntonBezemskiy commented on internal/server/saver/saver.go
> +// // Сохраняю метрики в буфер для последующей записи в файл
Удалил закомментированный код в 4ecd677e696dba1350739d70617154f9f3ef3a38  .
Надеюсь ничего, что все исправления в одном коммите сделал.

2024-08-05 08:03 UTC, tmvrus approved these changes

2024-08-05 08:15 UTC, merged